const IJNconsole = `
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
xllllllllllllllllllllllllllllllllllllllllllllllldKWW0olllllllllllllllllllllllllx
k,..............................................oNWk,.........................,k
WO;...........................................'xNNx'.........................;OW
MW0:.......;dkxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkk0WNd'.........................:0WM
MMMKc......'clllllllllllooooooooooooooooooodOWMWkc;;;;;;;;;;;;;;,..........cKMMM
MMMMXl.....................................:0WMMWNNNNNNNNNNNNNNKl.........lXMMMM
MMMMMNd'..................................cKMMMMMMMMMMMMMMMMMMXl........'dNMMMMM
MMMMMMNx'..'clllllllllllllllllloc'......,lXMMMMMMMMMMMMMMMMMMKc........'xNMMMMMM
MMMMMMMWk;:0WMMMMMMMMMMMMMMMMMMNx'....'d0NMMMMMMMMMMMMMMMMMW0:........,kWMMMMMMM
MMMMMMMMWXXMMMMMMMMMMMMMMMMMMMXo.....'xNMMMMMMMMMMMMMMMMMMWO;........;OWMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.....,kWMMMMMMMMMMMMMMMMMMWk,........:0WMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMKc.....;OWMMMMMMMMMMMMMMMMMMNd'........lKMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMXXMMMMW0:.....:0MMMMMMMMMMMMMMMMMMMXo.........oXMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMW0::0WMWO;.....cKMMMMMMMMMMMMMMMMMMMKl........'dNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWO;..;ONk,.....oXWXKKKKXXXXXXXXKKKXKO:........,xNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWO,....,:'....'dNNx;'''''''''''''''''.........;OWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM0:..........'xNNo...........................:0WMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWKc........,kWXl...........................cKMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMXl......;OWKc...........................lXMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMXo....:0W0:........,loddddddddddddddddkNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNd'.lKWO;........:0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWOxXNx,........cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNd'........oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMXc........oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMKc.......cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMXl.......:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'......;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'......,xXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,......';dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;........oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:........cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc........xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo......oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'..'dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

.------------------------------------------------------------------------------.
|                                                                              |
|                       Welcome to TheIceJI Website . . .                      |
|                                                                              |
'------------------------------------------------------------------------------'
`

export default IJNconsole